<?php
// $Id$
/**
 * Implementation of hook_help().
 */
function globalredirect_help($section) {
  switch ($section) {

    case 'admin/modules#description':
      return t('This module will do a 301 redirect for all nodes that have a URL Alias but are being accessed as a node. This will ensure that pages that have a URL Alias are only accessable from the aliased URL, thus ensuring your site doesnt end up in Google Sandpit for duplicate content.');
  }
}


function globalredirect_init() {
  if(isset($_REQUEST['q']) && function_exists('drupal_get_path_alias')) {
    //Check the current url (eg, node/123) for an alias... If set, redirect to it
    $alias = drupal_get_path_alias($_REQUEST['q']);
    if ($alias != $_REQUEST['q']) {
      header("HTTP/1.1 301 Moved Permanently");
      drupal_goto($alias);
      exit();
    }
    
    //Check if the current url ends in a slash (eg, node/123/)
    if(substr($_REQUEST['q'], -1) == "/") {
      //Ok - it does. Seeing as it didn't have an exact match WITH the slash in the above test, lets try without...
      $alias = drupal_get_path_alias(substr($_REQUEST['q'], 0, -1));
      if ($alias != $_REQUEST['q']) {
        //We matched an alias for the current URL with no slash - redirect to that...
        header("HTTP/1.1 301 Moved Permanently");
        drupal_goto($alias);
        exit();
      }
    }


    //Nothing above has been matched - lets do a check to compare the current url to the site's frontpage.
    //  If matches, redirect to the frontpage (eg, http://www.mysite.com/)
    $frontpage = variable_get('site_frontpage', '/');
    if($_REQUEST['q'] == $frontpage) {
      header("HTTP/1.1 301 Moved Permanently");
      drupal_goto('');
      exit();
    }
  }
}
?>
