<?php
/**
 * Implementation of hook_help().
 */
function globalredirect_help($section) {
  switch ($section) {

    case 'admin/modules#description':
      return t('This module will do a 301 redirect for all nodes that have a URL Alias but are being accessed as a node. This will ensure that pages that have a URL Alias are only accessable from the aliased URL, thus ensuring your site doesnt end up in Google Sandpit for duplicate content.');
  }
}


function globalredirect_init() {
  if(isset($_REQUEST['q']) && function_exists('drupal_lookup_path')) {
    $path = $_REQUEST['q'];
    
    $alias = drupal_lookup_path('alias', $path);
    
    if (!empty($alias)) {
      header("HTTP/1.1 301 Moved Permanently");
      drupal_goto($alias);
    }
  }
}
?>
